### ISSUE TITLE
Navbar highlighted page desyncs

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#165]
**Describe the bug**
Navbar on page load always highlights the Home page, regardless of what page the user is actually on.

**To Reproduce**
1. Using the Navbar, navigate to the forms page.
2. See that the "Forms" page is highlighted at the top
3. Refresh the page
4. See that the you are still on the forms page, but the navbar highlights the "Home" text

**Expected behavior**
Navbar should highlight the "Forms" text.

Possible fix: link the highlight to the `window.location` attribute (or something similar) rather than click events.

**Screenshots**
[Screencast from 05-19-2023 03:15:40 PM.webm](https://github.com/codeforpdx/PASS/assets/37914436/4990bbf9-bcd3-4062-8e49-1b3b058479ee)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by leekahung** [comment]
I believe the desync issue is being worked on in PR #143.

https://github.com/codeforpdx/PASS/assets/14917816/28a79d66-e115-4659-a849-ce3be184d9c2

It's getting close but it's still a bit quirky like how the line indicator has to jump several tabs before it gets to Inbox instead of just staying at Inbox. The color indicator is shown correctly though. It stayed at Inbox.

**Comment by xscottxbrownx** [comment]
Issue is technically resolved via PR #154  - other small issues remain.
