### ISSUE TITLE
Update Users feature to use WebIds instead of username

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#168]
**Is your feature request related to a problem? Please describe.**
Currently, the Users feature works using by tying usernames (timbot, jfelt, hunter2) to User information created by the case manager (first name, last name, etc). There is also logic to use these usernames to access the user's pod and interact with them. However, usernames are not what are used in Solid to identify pods owned by an individual; Solid uses WebIds (https://timbot.solidcommunity.net/profile/card#me, https://www.timsBlog/solidPod/card#me) to identify individuals.

The code for the users feature currently attempts to take the username and interpolate it into a WebId when it tries to access a user's pod. However, this only works if the user's real WebId is in the format the code expects. There's no requirement for WebId formats beyond that they be a valid URI. If the WebId is actually a different format, the code will fail. 

**Describe the solution you'd like**
We can avoid a lot of these issues by storing the user's WebId instead of a username.

**Describe alternatives you've considered**
The WebId is harder to input than a simple username, however this can be mitigated with some clever UI.
We can auto-add the protocol (`https://`) so the case manager doesn't need to put that in. Additionally, we could provide templates for the WebId formats of the most popular OIDC providers (the current template works in probably 90% of cases, but we'd like the system to work in 100% of cases)

**Additional context**
Currently, we're also storing some user information in the user system. However, the WebId is intended to point to a public`profile` document. It's possible that instead of storing a large amount of info on each individual user, PASS could fetch the user's personal profile and display it to the case manager. This could reduce the amount of information we'd need to store in the PASS system.

**Comment by leekahung** [comment]
I think having making the Solid Identity Provider flexible is a good idea since SOLID doesn't limit people to just one Provider. The initial thought was to limit PASS users to one "trusted" Provider at https://opencommons.net, but as we can see from our tests on solidcommunity.net, it doesn't have to be.

Full webId has been used for a brief time during early experimentation before it was switched for webId without "/profile/card#me". Only recently did we changed it to using username, hence why you see some of the more cryptic helper texts like, i.e. username without the <insert Solid provider name>. So the formatting of what we want at the end for users is still quite malleable.

I do think there could be another approach to this. One is to keep what we have now, but slowly build the other user's webId starting with their username. The default Solid Provider will be set to the one the user logs in from, but has the ability to adjust/change from an optional field. If used, the optional field will be used as the Solid Provider for the other user. Then "/profile/card#me" could be attached to make up the full webId.

"https://" + ${username} + ${ALTERNATIVE_PROVIDER ?? SOLID_IDENTITY_PROVIDER} + "/profile/card#me"

**Comment by timbot1789** [comment]
Yeah I'm thinking right now to have the user data object store both username and webid. Then when they add a username PASS generates a  webid from a template and displays it to the case manager. Then if the case manager wants to edit the generated ID, they can.

**Comment by timbot1789** [comment]
I'll code up something to this effect

**Comment by timbot1789** [comment]
The user feature design also lends itself well to a pod creation workflow. Case managers will probably be encountering people who haven't created pods before. If we create the pod for them, we can just create the pod with a username, and then receive the webid back from the Pod Service Provider. That would also dodge around the difficulties of inputting a long webid.

**Comment by leekahung** [comment]
Thanks Tim for taking the initiative!

**Comment by xscottxbrownx** [comment]
Is this complete? I see 2 linked PR's that have been merged, is there more to do?

**Comment by timbot1789** [comment]
> 

Yeah we finished this in the second PR. Closing
