### ISSUE TITLE
Update Login Button Styling

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#189]
**Is your feature request related to a problem? Please describe.**
Currently, we're using a red button for Login, which is fine as it brings attention to the user, but it looks out of place in the Navbar.

**Describe the solution you'd like**
Could update the styling of the button.

**Comment by Aryan123-rgb** [comment]
@leekahung Would like to work on this.

**Comment by leekahung** [comment]
> @leekahung Would like to work on this. 

Hey @Aryan123-rgb thanks for your interest in the project! While this is certainly a good place to start, however, this issue has been reserved for one of our newer team members.

Sorry for the inconvenience.

**Comment by Aryan123-rgb** [comment]
@leekahung Alright then

**Comment by andycwilliams** [comment]
> > @leekahung Would like to work on this.
> 
> Hey @Aryan123-rgb thanks for your interest in the project! While this is certainly a good place to start, however, this issue has been reserved for one of our newer team members.
> 
> Sorry for the inconvenience.

What is that team member's username? It would help clarify things by assigning this issue to them.

Edit: It would also help by providing a bit more detail about what we mean by updated style. New team members may not be familiar with our styling process to date. Particularly since our theme is not yet fully established.

They can consult the [Figma board](https://www.figma.com/file/BfsGjGbFUVvtqNq18sykoY/Pass-Project?type=design&node-id=1216%3A2986&t=DcAVJHcIUvsZwAxb-1) to begin with, then reach out to the UX team for any further questions.

**Comment by leekahung** [comment]
> > > @leekahung Would like to work on this.
> > 
> > 
> > Hey @Aryan123-rgb thanks for your interest in the project! While this is certainly a good place to start, however, this issue has been reserved for one of our newer team members.
> > Sorry for the inconvenience.
> 
> What is that team member's username? It would help clarify things by assigning this issue to them.

@Nick-Guzy  wasn't added yet until today so I couldn't really assign him.

**Comment by leekahung** [comment]
Closing issue for now.
