### ISSUE TITLE
Revamp Status Notification system

### ISSUE THREAD

**Issue by xscottxbrownx** [codeforpdx/PASS#301]
### Is your feature request related to a problem? Please describe.
Currently, all status notifications shown to the user are within the modals/forms that the user makes the action.  These should be it's own component/feature.

---

### Describe the solution you'd like
Most of the team agrees that using MUI's `snackbar` component seems to be a great approach.
We will still need some sort of indication that an action is occurring to the user (loading spinner/animation, etc.) before the snackbar with the end result is displayed.

---

### Additional context
Example of current notification system here on bottom of modal:
<img width="385" alt="Screenshot 2023-07-11 at 6 42 13 AM" src="https://github.com/codeforpdx/PASS/assets/71395931/226ae294-c1c8-450b-b146-af8d5460d78d">

Example of MUI snackbar:

https://github.com/codeforpdx/PASS/assets/71395931/bd0c160c-bfd1-4069-b7a8-a8c39e581575

**Comment by russfraze** [comment]
I created a BasicNotification component that renders a snackBar for messages. Severity can be passed as a prop to specify type. You can see it in action on this branch when adding and deleting clients. So far that is the only place I've implemented it for a test.  They display the same messages that appear in the deleteClient and addClient modals. 

Currently, this solution still relies on the notification-helper function and the statusReducer. I'm not sure if this issue is meant to revamp or simplify those aspects of the overall messaging system but I didn't see a need for that.

**Comment by russfraze** [comment]
@xscottxbrownx  @leekahung @timbot1789  @andycwilliams Added a progress spinner. The progress spinner adds another piece of state in each component that needs notifications. I used a generic circular spinner but there is a linear progress bar as well that might look nice.

**Comment by timbot1789** [comment]
@russfraze that sounds really good. Do you have a branch or PR for this?

**Comment by russfraze** [comment]
@timbot1789  Yes its named issue-301-Revamp-Status-Notifications

**Comment by andycwilliams** [comment]
Feel free to do a pull request anytime! You can do it as a draft in case you would like some feedback first

**Comment by leekahung** [comment]
Issue resolved. Snackbar implemented to Development. Closing issue.
