### ISSUE TITLE
Login onKeyUp not working

### ISSUE THREAD

**Issue by leekahung** [codeforpdx/PASS#334]
**Bug Description**:
At the moment, we have the `onKeyUp` attribute set up for the login button on PASS with the "Enter" key (OidcLoginComponent.jsx). However, it never gets triggered. Only the onClick works as intended.

Not urgent for MVP, but could be a good quality of life fix.

**Expected Behavior**:
To trigger login with the "Enter" key from the login page.

**Comment by xscottxbrownx** [comment]
I was going to make this issue today too, it really bugs me. Hahaha

**Comment by timbot1789** [comment]
@leekahung @xscottxbrownx 

I tested this a bit more locally, and the `onKeyUp` event on the button does actually work, you just need to focus on it (by tabbing over to it, you'll see the white focus bubble). This is actually a pretty common convention for keyboard navigation, so I think it's working appropriately.

There are a couple odd things though. The "click" animation doesn't play on enter, so it's hard to know if your action was received. And I don't think the tabstop ordering is correct on the home page either. Tabbing through the page seems to take me to mostly random elements.

It looks like @radhey30 just put up a PR for this, where they move the onKeyUp listener to the text field rather than the button. I'm not against this, but it does break keyboard navigation conventions.

**Comment by leekahung** [comment]
I believe there's a way to set the tab order for this in HTML called tabindex? We could set the button as first in the ordering then the text field for the Solid server, then any other focusable links or elements going left to right, up to down

**Comment by timbot1789** [comment]
Other way around. text field first, login button second. Tab index should go left -> right and top -> bottom.

**Comment by leekahung** [comment]
Want thinking about using the default server as the default option (with only advanced users wanting to change servers), so shouldn't the ordering be better with the button first then the textfield? With the rest following the standard convention left to right, top to down.

**Comment by timbot1789** [comment]
It's best to adopt the general web conventions unless we have strong reason not to.

Left -> Right, Top -> Down is a pretty widely established keyboard accessibility convention:
https://webaim.org/techniques/keyboard/
https://www.w3.org/WAI/fundamentals/accessibility-principles/#keyboard

**Comment by leekahung** [comment]
Was wondering if we should swap the placement of the button and textfield if we want to keep the convention since from the user's perspective, it'll be good if they could simply enter in from the login page, similar to the authorize page.

**Comment by timbot1789** [comment]
That could work

**Comment by leekahung** [comment]
Issue resolved in PR #340 with onKeyUp being moved to Login TextField instead of Login Button. Closing issue.
