### ISSUE TITLE
Enhancement: Add logo to PASS tab in web browser

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#336]
**Describe the Current Behavior/Feature**:
Currently, when running PASS in a web browser, the tab doesn't display any particularly interesting icon. Just the browser default

![image](https://github.com/codeforpdx/PASS/assets/37914436/46cd55d8-b9a6-45fc-bed8-43512bb0b408)

**Proposed Behavior/Feature**:
We can display a nice icon here instead. A clean PASS logo in an SVG format would be perfect

**Proposed Implementation (if applicable)**:
To do this, all we need to do is drop a `favicon.ico` in the folder. W3 schools describes how to do this here:
https://www.w3schools.com/html/html_favicon.asp

**Comment by Raspber** [comment]
i will handle the favicon

**Comment by xscottxbrownx** [comment]
> i will handle the favicon

where are we at on this?

**Comment by Raspber** [comment]
> > i will handle the favicon
> 
> where are we at on this?

Hello Scott, I belive i did this already with the logo in the navbar issue.

**Comment by Raspber** [comment]
This is what i submitted, 
![Screenshot 2023-08-07 131626](https://github.com/codeforpdx/PASS/assets/20136800/97bb5848-c952-40ae-8889-4c34d30de8e6)
and this is what i have now, i created a landing page for when users arent logged in,
![Screenshot 2023-08-07 132304](https://github.com/codeforpdx/PASS/assets/20136800/38475e0a-094d-45f2-8d7d-f414a2c2d668)
but i havent created a pr yet because I want to show it at the meeting.

**Comment by xscottxbrownx** [comment]
> but i havent created a pr yet because I want to show it at the meeting.

That explains it!
I knew I saw it somewhere. We just haven't finished up/approved that PR yet.

**Comment by leekahung** [comment]
Was thinking of keeping this open because of the Landing page design. But think we could move it in a new Issue. For now, I'm closing this since the issue for adding a new PASS logo has been resolved.
