### ISSUE TITLE
[Feature Request] - Add "Sign up with existing POD" option to the Sign up page

### ISSUE THREAD

**Issue by timbot1789** [codeforpdx/PASS#586]
### Feature Description:
Currently, if you click the signup button in PASS, or if you get an invite link from a PASS user, your only option is to create a new pod. We should allow people to sign up with an existing pod as well.

The page currently looks like this:
<img width="602" alt="Screenshot 2024-03-03 at 3 19 59 PM" src="https://github.com/codeforpdx/PASS/assets/37914436/c625bbbf-209f-407f-8121-80aec9ddb4fe">

We should add a new form underneath that lets a user put in their existing pod:
<img width="593" alt="Screenshot 2024-03-03 at 3 24 17 PM" src="https://github.com/codeforpdx/PASS/assets/37914436/fb74988e-e832-493f-923a-a49d6945bfb0">

The POD Provider area will take in the URL of the user's chosen pod provider. Once inputting this, they can click the login button to be directed to their provider for sign-in. This flow will be very similar to the current login to PASS flow. Once they are signed in, they will be redirected back to PASS, where we can begin the same POD setup flow we do when creating a new POD. Both flows, the "Get a new POD" signup and the "use an existing POD" signup, should end at the same screen, the `ShowNewPod` component, which currently looks like this:
<img width="880" alt="Screenshot 2024-03-03 at 3 27 02 PM" src="https://github.com/codeforpdx/PASS/assets/37914436/1e6cda08-cb31-4c67-9e11-0f59395ba514">

Improvements to this screen are out of scope of this issue.

**Comment by russfraze** [comment]
@timbot1789 Hey Tim, 

I created a branch for this issue and the form which looks like this: 
![Screenshot 2024-03-21 at 1 07 27 PM](https://github.com/codeforpdx/PASS/assets/81979567/99c3b8d4-d7dc-459c-8a94-5aa0c13b250c)


You mentioned that the flow of this is similar to Login to Pass. I'm looking in the OidcLoginComponent in the Navbar, and I'm thinking we need a similar login handler, but instead of the oidcIssuer that comes from the default or the dropdown, we need the url thats typed by the user.  Please let me know if I'm on the right track with that. 

Heres how my component looks but feel free to check out the branch:

![Screenshot 2024-03-21 at 1 20 19 PM](https://github.com/codeforpdx/PASS/assets/81979567/4793d3d0-7fdc-4c0c-9052-1336e219069a)

**Comment by russfraze** [comment]
@leekahung looping you in to check this out.

**Comment by leekahung** [comment]
> @leekahung looping you in to check this out. 

I'm not too sure, but I believe this second flow should feel more like logging into your own Pod if you already have one, so that you can register your Pod with the invite link from another person rather than needing to make a new one.

Post-sign in through this link should navigate you to the register successful page rather than to contacts directly, but you'll also be logged in, I think?
